site_name: 小黑屋
# theme: readthedocs
nav:
    - 首页: index.md
    - Android:
      - StrictMode: strictMode.md
      - 触摸事件分发: touchEventDispatch.md
      - adb模拟屏幕触摸: adb_input.md
      - Android渠道写入方式: android_flavor.md
      - Annotation注解处理器: annotation.md
      - 注解处理器调试: annotation_debug.md
      - Glide知识点: glide.md
      - lightKV: lightKV.md
      - MMKV: mmkv.md
      - Webview:
        - 缓存机制: webview_cache.md
        - 和Native通信: webview_native.md
        - 漏洞: webview_bug.md
        - 优化: webview_optmize.md
      - 代码片段:
        - 微信气泡: code/bubble_view.md  
    - 工具:
      - FFMPEG: ffmpeg.md
      - DMG: dmg.md
    - Java:
      - 内存映射: mmap.md  
      - JavaPoet: java_poet.md
    - 收藏: bookmark.md

