site_name: 小黑屋
##theme: gitbook
theme: readthedocs
nav:
    - 首页: index.md
    - Android:
      - 编译/脚本:
        - Annotation注解处理器: annotation.md
        - 注解处理器调试: annotation_debug.md
        - Android渠道写入方式: android_flavor.md
      - 框架:
        - Glide: glide.md
        - lightKV: lightKV.md
        - MMKV: mmkv.md
        - EventBus: eventbus.md
        - OkHttp: okhttp.md
        - OkHttp-Dns: okhttp_dns.md
        - Okhttp重试机制: okhttp_retry.md
        - BlockCanary: blockCanary.md
        - LeakCanary: leakCanary.md
        - RxJava: rxjava.md
        - GreenDao: greendao.md
      - 系统分析:
        - StrictMode: strictMode.md
        - 触摸事件分发: touchEventDispatch.md
        - 动画: android_animation.md
      - Webview:
        - 缓存机制: webview_cache.md
        - 和Native通信: webview_native.md
        - 漏洞: webview_bug.md
        - 优化: webview_optmize.md
      - 代码片段:
        - 微信气泡: code/bubble_view.md
        - zbar: zbar.md
      - 适配:
        - 系统适配: dev_compat.md
      - 多媒体:
        - RenderScript: renderscript.md
      - 安全:
        - 建议: android_safe.md
        - 风险点: android_danger.md
      - 工具:
        - adb模拟屏幕触摸: adb_input.md
        - tcpdump: tcpdump.md
      - 热修复:
        - Transform: transform.md
        - ClassLoader: classloader.md  
        - Instant Run: instantRun.md
        - Robust: robust.md
        - 热修复方案: hotFix.md
        - ASM: asm.md
      - 未分类:
        - 应用保活: keepAlive.md
      - 性能优化:
        - Bitmap: bitmap.md
        - Anr: anr.md
    - 网络:
      - SNI: sni.md        
    - 工具:
      - FFMPEG: ffmpeg.md
      - DMG: dmg.md
    - Java:
      - 内存映射: mmap.md  
      - JavaPoet: java_poet.md
      - Volatile: volatile.md
      - AspectJ: aspectJ.md
      - Collections: java_collections.md
      - access$xxx: class_access.md
      - Concurrent:
        - volatile: volatile.md
      - 线程池: threadPool.md  
      - 泛型通配符: java_generic.md
    - 虚拟机:
      - 内存模型: jvm.md
    - 收藏: bookmark.md

